events {}

http {
    upstream flask_app {
        server app:5000;
    }

    upstream frontend {
        server frontend:3000;
    }

    server {
        listen 80;

        # API → Flask
        location /api/ {
            proxy_pass http://flask_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_connect_timeout 5s;
            proxy_read_timeout 35s;
            proxy_send_timeout 35s;
        }

        # Всё остальное → React SPA
        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
